### ISSUE TITLE
Highlight Polygons

### ISSUE THREAD

**Issue by paragemini** [crazycapivara/deckgl#199]
Hello, I've the below visualization created using deck.gl package in R.

https://paragemini.github.io/

Is there an option to highlight the polygons when the tooltip gets updated? Something like the black highlights occur when the mouse hovers over the polygons 

https://rstudio.github.io/leaflet/choropleths.html

Thanks for the wonderful package

**Comment by crazycapivara** [comment]
@paragemini Yes, this is possible, just add the following properties to your layer:

```r
props <- list(
   pickable = TRUE, # only needed if no tooltip is used
   autoHighlight = TRUE,
   # highlightColor = c(120, 40, 30) # optional to set the color
   # ...
)
```
