### ISSUE TITLE
Seems overlay with mapdeck

### ISSUE THREAD

**Issue by harryprince** [crazycapivara/deckgl#63]
deckgl seems overlay with mapdeck？

https://github.com/SymbolixAU/mapdeck

**Comment by crazycapivara** [comment]
I think it uses more or less leaflet syntax, in leaflet you can also pass the `data` parameter to the `add_*` functions. In leaflet `setView` is optional, whereas in `deckgl` an initial view state should always be set.

**Comment by crazycapivara** [comment]
overlay see #64

**Comment by crazycapivara** [comment]
I will close this one because it is discussed in the issue mentioned above.
