### ISSUE TITLE
how create coordinates that include c(lng,lat) in a column?

### ISSUE THREAD

**Issue by liygzting** [crazycapivara/deckgl#86]
@crazycapivara  hi，

Something's bothering me

when I run the code:
url0 <- paste0(
  "https://raw.githubusercontent.com/",
  "uber-common/deck.gl-data/",
  "master/website/bart-stations.json"
)
sample_data<-fromJSON(url0)

and I get a dataframe like this:
> head(sample_data)
                                 name code                                     address
1                    Lafayette (LAFY)   LF     3601 Deer Hill Road, Lafayette CA 94549
2 12th St. Oakland City Center (12TH)   12             1245 Broadway, Oakland CA 94612
3             16th St. Mission (16TH)   16 2000 Mission Street, San Francisco CA 94110
4             19th St. Oakland (19TH)   19             1900 Broadway, Oakland CA 94612
5             24th St. Mission (24TH)   24 2800 Mission Street, San Francisco CA 94110
6                        Ashby (ASHB)   AS      3100 Adeline Street, Berkeley CA 94703
  entries exits            coordinates
1    3481  3616 -122.123801, 37.893394
2   13418 13547 -122.271604, 37.803664
3   12409 12351 -122.419694, 37.765062
4   13108 13090 -122.269029, 37.807870
5   12817 12529 -122.418466, 37.752254
6    5452  5341 -122.269780, 37.853024

the  coordinates  include lng and lat
How am I going to generate new coordinates like that ?

ps: raw data as below
> head(dt[,.(vin,lng,lat)])
                 vin         lng         lat
1: L6T792423JN451621 121.2295550 30.33141889
2: L6T792423JN451621 121.2368408 30.34006500
3: L6T792423JN451621 121.6590389 29.73693583
4: L6T792423JN451621 121.6553528 29.73500694
5: L6T792423JN451621 121.2299058 30.33186083
6: L6T792423JN451621 121.2268678 30.32662194

or https://crazycapivara.github.io/deckgl/articles/icon-layer.html
when I creatte icon-layer, is data must be  JSON?

Thanks a million
Thanks a million

**Comment by crazycapivara** [comment]
Hi,

data must NOT be JSON. Sorry, I have to update the docs showing how to use R data objects.

You just need to pass the column names for _lat_ and _lng_ via `get_position` R function, e. g.

scatterplot:

``` r
deckgl(latitude = -24.655, longitude = 176.9, zoom = 4) %>%
   add_scatterplot_layer(
      data = quakes,
      getPosition = get_position("lat", "long"),
      getRadius = JS("d => d.mag * 100"),
      radiusScale = 60,
      getColor = JS("d => [Math.sqrt(d.depth) * 20, 130, 10]")
   )
```

icon:

``` r
deckgl(latitude = -24.655, longitude = 176.9, zoom = 4) %>%
   add_icon_layer(
      data = quakes,
      getPosition = get_position("lat", "long"),
      getSize = get_property("mag"),
      getColor = JS("d => [Math.sqrt(d.depth) * 20, 130, 10]")
   )
```

**Comment by crazycapivara** [comment]
Another example using data from the `deckgl` package

``` r
sample_data <- deckgl::bart_stations

sample_data$radius <- sqrt(sample_data$exits)

properties <- list(
  getPosition = get_position("lat", "lng"),
  getRadius = get_property("radius"),
  radiusScale = 6,
  getColor = c(255, 140, 20)
)

deck <- deckgl(zoom = 10.5, pitch = 35) %>%
  add_scatterplot_layer(data = sample_data, properties = properties) %>%
  add_mapbox_basemap()

if (interactive()) deck
```

**Comment by crazycapivara** [comment]
[see also road-safety-example](https://github.com/crazycapivara/deckgl/blob/master/inst/examples/deckgl-examples/grid-layer_road-safety-in-uk.R)

**Comment by liygzting** [comment]
It really helped
Many thanks @crazycapivara

**Comment by liygzting** [comment]
> Another example using data from the `deckgl` package
> 
> ```r
> sample_data <- deckgl::bart_stations
> 
> sample_data$radius <- sqrt(sample_data$exits)
> 
> properties <- list(
>   getPosition = get_position("lat", "lng"),
>   getRadius = get_property("radius"),
>   radiusScale = 6,
>   getColor = c(255, 140, 20)
> )
> 
> deck <- deckgl(zoom = 10.5, pitch = 35) %>%
>   add_scatterplot_layer(data = sample_data, properties = properties) %>%
>   add_mapbox_basemap()
> 
> if (interactive()) deck
> ```

hi @crazycapivara 
Some other questions：

> head(a)
        lng       lat
1 116.71148 39.434895
2 116.71148 39.434895
3 116.71148 39.434895
4 116.71144 39.435100
5 116.71144 39.435060
6 116.71140 39.435090

How to get path,  Is get_position still valid?

when I try that ,I get nothing
code as follow:
properties <- list(
  pickable = TRUE,
  widthScale = 20,
  widthMinPixels = 2,
  getPosition = get_position("lat", "lng"),
  getColor = c(255, 140, 20),
  getWidth = 5
  # ,getTooltip = get_property("pd")
)

deck <- deckgl(latitude = 38.38687967,longitude = 114.42064498,pitch = 25, zoom = 5.5) %>%
  add_path_layer(data = a, properties = properties) %>%
  add_mapbox_basemap()

if (interactive()) deck

**Comment by liygzting** [comment]
properties <- list(
  pickable = TRUE,
  widthScale = 20,
  widthMinPixels = 2,
  getPosition = get_position("lat", "lng"),
  getColor = c(255, 140, 20),
  getWidth = 5
)

deck <- deckgl(latitude = 38.38687967,longitude = 114.42064498,pitch = 25, zoom = 5.5) %>%
  add_path_layer(data = a, properties = properties) %>%
  add_mapbox_basemap()

if (interactive()) deck

**Comment by crazycapivara** [comment]
Hi @liygzting,
you need to use the right data format as specified in [deckgl-path-layer-api-reference](https://github.com/uber/deck.gl/blob/master/docs/layers/path-layer.md):

```javascript
// Data format:
[
      {
        path: [[-122.4, 37.7], [-122.5, 37.8], [-122.6, 37.85]],
        name: 'Richmond - Millbrae',
        color: [255, 0, 0]
      },
      ...
]
```

Furthermore, you need to use the `getPath` property as shown in the docs.

So, you need a list column in your `data.frame` containing the coords of the path(es).

Here is an example using the `bart_stations` data set:

```r
coords <- deckgl::bart_stations[, c("lng", "lat")] %>%
  as.matrix()

data <- tibble::tibble(
  tooltip = "Bart Stations",
  path = list(coords)
)

# Check, if your data format is correct
jsonlite::toJSON(data) %>% print()

properties <- list(
  pickable = TRUE,
  widthScale = 20,
  widthMinPixels = 2,
  getPath = get_property("path"),
  getColor = c(250, 140, 20),
  getWidth = 5,
  getTooltip = get_property("tooltip")
)

deckgl(zoom = 9, pickingRadius = 20) %>%
  add_path_layer(data = data, properties = properties) %>%
  add_icon_layer(
    data = bart_stations,
    getPosition = get_position("lat", "lng"),
    getColor = c(10, 140, 50),
    getTooltip = get_property("name")
  )
```

**Comment by crazycapivara** [comment]
Alternatively, you can create the data using a _list_ of _lists_:

```r
coords <- deckgl::bart_stations[, c("lng", "lat")] %>%
  as.matrix()

data <- list(
  list(
    tooltip = "Bart Stations",
    path = coords
  )
)

```

**Comment by liygzting** [comment]
thanks @crazycapivara ,
for path , scatter,icon or grid etc,  I change data to tibble not dataframe so that i can plot most of layer.
Does that mean you can just use this？
Or is there anything else to notice？

**Comment by crazycapivara** [comment]
Nope, you can use `data.frame`. A `tibble` is just a variant and often more comfortable to handle. That's why I prefer it, e. g. when using `list` columns. Here is how to create a `data.frame` with `list` column which works fine:

```r
# coords same as above
df <- data.frame(
  tooltip = "Bart Stations",
  path = I(list(coords))
)
```
For all layers expecting point data it's fine to have a `data.frame` with `lat` and `lng` columns.

It is planned to support `sf` objects, see #81.

**Comment by liygzting** [comment]
thanks @crazycapivara 
It really makes sense
Since you told me this good method, I decided to start using tibble too.
